### ISSUE TITLE
 [Mac-크롬 브라우저-전체화면-게시글 작성 및 수정] 게시글 내용 도배 시 게시글 생성 안됨

### ISSUE THREAD

**Issue by miginho12** [mingoo36/5-covy-lee-community-fe#10]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.
게시글 내용을 길~~~게 작성하면 오류가 생깁니다.

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/50b7273a-4356-4bba-9c3e-99701a92bdf4" />

**Comment by mingoo36** [comment]
게시글 내용은 최대 5000자로 제한으로 해결했슴당
