### ISSUE TITLE
 [macOS-Chrome-게시글 상세조회] 댓글 작성

### ISSUE THREAD

**Issue by ingyulim** [mingoo36/5-covy-lee-community-fe#11]
**버그 설명**
댓글 작성, 수정 시 띄어쓰기 적용x

**스크린샷**
<img width="965" alt="image" src="https://github.com/user-attachments/assets/96e4d075-221b-44db-aded-bc6a8090d941" />

<img width="728" alt="image" src="https://github.com/user-attachments/assets/4e5effe9-16a6-4757-a620-88c2af368955" />

**Comment by mingoo36** [comment]
.replace(/\n/g, "<br>");
게시글 내용을 서버로 전송할때  \n 입력을 <br>로 바꿔서 처리
