### ISSUE TITLE
[mac-chrome-2560px-'상세페이지'] 댓글수, 조회수

### ISSUE THREAD

**Issue by ingyulim** [mingoo36/5-covy-lee-community-fe#12]
**버그 설명**
새로고침을 할 때 가끔 댓글수, 조회수가 뜨지 않는 사소?한 문제 발견

**스크린샷**
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/111f0391-e0c1-40e2-a8b1-228139fdf508" />

**Comment by mingoo36** [comment]
조회수 로직에 redis 사용 
2시간마다 조회수가 증가하도록 수정완료
