### ISSUE TITLE
[MacOS-chrom-비밀번호 변경] - 대문자+소문자+숫자+특수기호 입력했는데 변경 안되는 이슈 .. 

### ISSUE THREAD

**Issue by juyeon320** [mingoo36/5-covy-lee-community-fe#13]
<img width="430" alt="image" src="https://github.com/user-attachments/assets/3b084b19-178e-45c7-b426-875f62af42cb" />
 비밀번호 변경이 안됩니당..
변경 시도한 비밀번호 : Aasdf1234^

**Comment by mingoo36** [comment]
저번에 비밀번호 규칙을 수정했는데 프론트만 수정했어서 이런 오류가 생겼네요 백앤드도 수정했습니당
