### ISSUE TITLE
 [MAC-크롬-전체화면-상세페이지] 뒤로가기 버튼 이슈

### ISSUE THREAD

**Issue by miginho12** [mingoo36/5-covy-lee-community-fe#14]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.
게시물을 삭제하고, 뒤로가기 버튼을 클릭 시 삭제했던 게시물의 상세페이지로 이동이 됩니다. 그리고 한번 더 뒤로가기 버튼을 누르면 게시물 목록에 삭제한 게시물이 있고, 접근하면 게시글을 불러오는 데 문제가 발생했습니다. 라는 오류 메시지와 함께 접근할 수 없는데, 사용자가 새로고침하지 않고도 사용자가 작업을 끝낸 이후에 자동으로 새로고침이 되도록 하는 것이 좋을 것 같습니다. 그리고 뒤로가기 버튼에 대한 처리도 필요해보입니다.

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
 
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/8d72223e-85e7-4f35-b4dc-96960531f13d" />

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/8d5c9f5a-f35c-4e0d-b905-7a58f4728151" />

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/298cc5f1-8cef-40d0-9842-2950b9e70de4" />

**Comment by mingoo36** [comment]
window.location.replace() 사용해서 브라우저 기록을 남기지 않는 방향으로 수정 완료
