### ISSUE TITLE
 [OS-브라우저-가로사이즈-'상세페이지'] 댓글 수정

### ISSUE THREAD

**Issue by ingyulim** [mingoo36/5-covy-lee-community-fe#15]
**버그 설명**
띄어쓰기가 있는 댓글의 경우, 수정을 하려고 할 때 띄어쓰기가 풀림.

**스크린샷**
<img width="467" alt="image" src="https://github.com/user-attachments/assets/8909b2a8-6680-4319-b4a5-f536cf6f9bdf" />

<img width="474" alt="image" src="https://github.com/user-attachments/assets/d09b07f7-fe61-4e63-968b-860873422fa7" />

**Comment by mingoo36** [comment]
기존 댓글 내용을 가져올때 <br> 태그를 다시 줄바꿈 문자(\n) 로 변환하도록 수정!
