### ISSUE TITLE
 [MAC-크롬 브라우저-전체화면-스크롤 페이지 모두] 헤더 레이아웃 겹침 이슈

### ISSUE THREAD

**Issue by miginho12** [mingoo36/5-covy-lee-community-fe#2]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.
스크롤이 가능한 화면에서는 헤더가 게시물을 가리는 이슈가 생깁니다.

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/0b5e49a4-95df-4230-9f1f-1d33d44bcbc2" />

**Comment by mingoo36** [comment]
헤더 배경에 색을 넣어서 보완완료
