### ISSUE TITLE
 [MacOS-chrom-로그인] 로그인시 ^ 특수문자 인식 불가

### ISSUE THREAD

**Issue by juyeon320** [mingoo36/5-covy-lee-community-fe#3]
<img width="550" alt="image" src="https://github.com/user-attachments/assets/93379b7b-9eb1-4131-a1b0-5fee1c2a4c5a" />

로그인시 ^ 특수문자 인식 불가
-> 회원가입은 가능했습니다!

**Comment by mingoo36** [comment]
다른 특수문자들 로그인, 회원가입시 허용완료

**Comment by mingoo36** [comment]
+ 비밀번호 수정 시에도 추가
