### ISSUE TITLE
 [mac-chrome-게시글상세] 이미지 비율 css

### ISSUE THREAD

**Issue by from-minju** [mingoo36/5-covy-lee-community-fe#4]
**버그 설명**
게시글 이미지의 가로세로 비율이 원본 이미지대로 나오면 더 좋을것 같습니다!

**스크린샷**
<img width="1732" alt="image" src="https://github.com/user-attachments/assets/c47aff67-b9b4-446c-a0e6-768a0e09ede1" />

**Comment by mingoo36** [comment]
이미지가 원본 비율 유지하도록 css postImage 수정완료
