### ISSUE TITLE
 [Mac-크롬 브라우저-전체화면-게시글 수정] 게시글 수정 시 선택된 이미지 안보임

### ISSUE THREAD

**Issue by miginho12** [mingoo36/5-covy-lee-community-fe#5]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.
게시글 수정 시 이미지가 첨부되어 있는건지 안보입니다. (선택된 파일 없음이라고 뜨네요)

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/c0da1fcd-fccd-4e91-88c6-6dda47f94f9c" />

**Comment by mingoo36** [comment]
수정완료!
