### ISSUE TITLE
 [MAC-크롬 브라우저-전체화면-게시글 상세 보기 페이지] 시간 레이아웃 틀어짐 이슈

### ISSUE THREAD

**Issue by miginho12** [mingoo36/5-covy-lee-community-fe#6]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.
수정 삭제 버튼이 안보여지면서 레이아웃이 틀어지는 이슈가 있습니다.

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="651" alt="image" src="https://github.com/user-attachments/assets/b2650e0e-9355-49bd-9623-010f3068257d" />

**Comment by mingoo36** [comment]
수정완료!
