### ISSUE TITLE
 [mac-chrome-회원정보수정] 프로필사진만 수정 불가

### ISSUE THREAD

**Issue by from-minju** [mingoo36/5-covy-lee-community-fe#7]
**버그 설명**
회원정보수정에서 프로필 사진만 변경 불가함.
닉네임 안바꾸고 사진만 변경하려고 하면 "이미 사용중인 사용자 이름입니다"라고 뜨며 수정버튼 활성화 안됨.

**스크린샷**
<img width="1776" alt="image" src="https://github.com/user-attachments/assets/97f75b80-9492-444e-b708-e90df9f6a703" />

**Comment by mingoo36** [comment]
분리해서 수정했슴니당
