### ISSUE TITLE
 [MacOS-chrom-회원정보수정] 비밀번호 변경 후 로그인 다시 하라는 안내가 필요해 보입니다.

### ISSUE THREAD

**Issue by juyeon320** [mingoo36/5-covy-lee-community-fe#8]
<img width="576" alt="image" src="https://github.com/user-attachments/assets/73a14958-a1a5-4f91-98bc-8700208efbf8" />
비밀번호 변경 후 로그인 다시 하라는 안내가 필요해 보입니다.

**Comment by mingoo36** [comment]
로그아웃 api 호출하고 로그인페이지로 리다이랙션하게 구현했습니당
